version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-net
    volumes:
      - data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-net
    expose:
      - 6379
    restart:
      always

volumes:
  data:

networks:
  app-net:
    driver: bridge