on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.SERVER }}
      PORT: ${{ secrets.PORT }}
      SALT: ${{ secrets.SALT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
    strategy:
      max-parallel: 4
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn test
        env:
          DATABASE_NAME: USER_API
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          DATABASE_PORT: 5432
          DATABASE_HOST: localhost
          REDIS_HOST: redis
